// generated by goxsd; DO NOT EDIT

package Fare_InformativePricingWithoutPNR_v19_1 // tipnrq191

import "encoding/xml"

// Fare_InformativePricingWithoutPNR is generated from an XSD element
type FareInformativePricingWithoutPNR struct {
	XMLName            xml.Name           `xml:"http://xml.amadeus.com/TIPNRQ_19_1_1A Fare_InformativePricingWithoutPNR"`
	OriginatorGroup    originatorGroup    `xml:"originatorGroup"`
	PassengersGroup    []PassengersGroup  `xml:"PassengersGroup"`
	SegmentGroup       []SegmentGroup     `xml:"SegmentGroup"`
	PricingOptionGroup pricingOptionGroup `xml:"pricingOptionGroup"`
}

// originatorGroup is generated from an XSD element
type originatorGroup struct {
	AdditionalBusinessInformation additionalBusinessInformation `xml:"additionalBusinessInformation"`
}

// additionalBusinessInformation is generated from an XSD element
type additionalBusinessInformation struct {
	SourceType        sourceType        `xml:"sourceType"`
	OriginatorDetails originatorDetails `xml:"originatorDetails"`
	LocationDetails   locationDetails   `xml:"locationDetails"`
	CountryCode       string            `xml:"countryCode"`
	SystemCode        string            `xml:"systemCode"`
}

// sourceType is generated from an XSD element
type sourceType struct {
	SourceQualifier1 string `xml:"sourceQualifier1"`
	SourceQualifier2 string `xml:"sourceQualifier2"`
}

// originatorDetails is generated from an XSD element
type originatorDetails struct {
	OriginatorID           int    `xml:"originatorId"`
	InHouseIDentification1 string `xml:"inHouseIdentification1"`
	InHouseIDentification2 string `xml:"inHouseIdentification2"`
	InHouseIDentification3 string `xml:"inHouseIdentification3"`
}

// locationDetails is generated from an XSD element
type locationDetails struct {
	TrueLocationID string `xml:"trueLocationId"`
	TrueLocation   string `xml:"trueLocation"`
}

// PassengersGroup is generated from an XSD element
type PassengersGroup struct {
	SegmentRepetitionControl SegmentRepetitionControl `xml:"SegmentRepetitionControl"`
	TravellersID             TravellersID             `xml:"TravellersID"`
	DiscountPtc              DiscountPtc              `xml:"DiscountPtc"`
}

// SegmentRepetitionControl is generated from an XSD element
type SegmentRepetitionControl struct {
	SegmentControlDetails SegmentControlDetails `xml:"SegmentControlDetails"`
}

// SegmentControlDetails is generated from an XSD element
type SegmentControlDetails struct {
	Quantity      int `xml:"quantity"`
	NumberOfUnits int `xml:"numberOfUnits"`
}

// TravellersID is generated from an XSD element
type TravellersID struct {
	TravellerDetails []TravellerDetails `xml:"TravellerDetails"`
}

// TravellerDetails is generated from an XSD element
type TravellerDetails struct {
	MeasurementValue int `xml:"measurementValue"`
}

// DiscountPtc is generated from an XSD element
type DiscountPtc struct {
	ValueQualifier string       `xml:"valueQualifier"`
	FareDetails    *FareDetails `xml:"FareDetails"`
	IDentityNumber string       `xml:"identityNumber"`
}

// FareDetails is generated from an XSD element
type FareDetails struct {
	Qualifier string `xml:"qualifier"`
}

// SegmentGroup is generated from an XSD element
type SegmentGroup struct {
	SegmentInformation        SegmentInformation        `xml:"SegmentInformation"`
	AdditionnalSegmentDetails additionnalSegmentDetails `xml:"additionnalSegmentDetails"`
	Inventory                 inventory                 `xml:"inventory"`
}

// SegmentInformation is generated from an XSD element
type SegmentInformation struct {
	FlightDate           FlightDate           `xml:"FlightDate"`
	BoardPointDetails    PointDetails         `xml:"BoardPointDetails"`
	OffpointDetails      PointDetails         `xml:"offpointDetails"`
	CompanyDetails       CompanyDetails       `xml:"CompanyDetails"`
	FlightIDentification FlightIDentification `xml:"flightIdentification"`
	FlightTypeDetails    FlightTypeDetails    `xml:"FlightTypeDetails"`
	ItemNumber           int                  `xml:"itemNumber"`
	SpecialSegment       string               `xml:"specialSegment"`
}

// FlightDate is generated from an XSD element
type FlightDate struct {
	DepartureDate string `xml:"departureDate"`
	DepartureTime string `xml:"departureTime"`
	ArrivalDate   string `xml:"arrivalDate"`
	ArrivalTime   string `xml:"arrivalTime"`
}

// BoardPointDetails is generated from an XSD element
type PointDetails struct {
	TrueLocationID string `xml:"trueLocationId"`
}

//// offpointDetails is generated from an XSD element
//type offpointDetails struct {
//	TrueLocationID string `xml:"trueLocationId"`
//}

// CompanyDetails is generated from an XSD element
type CompanyDetails struct {
	MarketingCompany string `xml:"marketingCompany"`
	OperatingCompany string `xml:"operatingCompany"`
}

// FlightIDentification is generated from an XSD element
type FlightIDentification struct {
	FlightNumber string `xml:"flightNumber"`
	BookingClass string `xml:"bookingClass"`
}

// FlightTypeDetails is generated from an XSD element
type FlightTypeDetails struct {
	FlightIndicator string `xml:"flightIndicator"`
}

// additionnalSegmentDetails is generated from an XSD element
type additionnalSegmentDetails struct {
	LegDetails legDetails `xml:"legDetails"`
}

// legDetails is generated from an XSD element
type legDetails struct {
	Equipment     string `xml:"equipment"`
	NumberOfStops int    `xml:"numberOfStops"`
}

// inventory is generated from an XSD element
type inventory struct {
	BookingClassDetails bookingClassDetails `xml:"bookingClassDetails"`
}

// bookingClassDetails is generated from an XSD element
type bookingClassDetails struct {
	Designator         string `xml:"designator"`
	AvailabilityStatus string `xml:"availabilityStatus"`
	SpecialService     string `xml:"specialService"`
}

// pricingOptionGroup is generated from an XSD element
type pricingOptionGroup struct {
	PricingOptionKey         pricingOptionKey         `xml:"pricingOptionKey"`
	OptionDetail             optionDetail             `xml:"optionDetail"`
	CarrierInformation       carrierInformation       `xml:"carrierInformation"`
	Currency                 currency                 `xml:"currency"`
	PenDisInformation        penDisInformation        `xml:"penDisInformation"`
	MonetaryInformation      monetaryInformation      `xml:"monetaryInformation"`
	TaxInformation           taxInformation           `xml:"taxInformation"`
	DateInformation          dateInformation          `xml:"dateInformation"`
	FrequentFlyerInformation frequentFlyerInformation `xml:"frequentFlyerInformation"`
	FormOfPaymentInformation formOfPaymentInformation `xml:"formOfPaymentInformation"`
	LocationInformation      locationInformation      `xml:"locationInformation"`
	PaxSegTstReference       paxSegTstReference       `xml:"paxSegTstReference"`
	OfferReferences          offerReferences          `xml:"offerReferences"`
	ElementManagementData    elementManagementData    `xml:"elementManagementData"`
}

// pricingOptionKey is generated from an XSD element
type pricingOptionKey struct {
	PricingOptionKey string `xml:"pricingOptionKey"`
}

// optionDetail is generated from an XSD element
type optionDetail struct {
	CriteriaDetails criteriaDetails `xml:"criteriaDetails"`
}

// criteriaDetails is generated from an XSD element
type criteriaDetails struct {
	AttributeType        string `xml:"attributeType"`
	AttributeDescription string `xml:"attributeDescription"`
}

// carrierInformation is generated from an XSD element
type carrierInformation struct {
	CompanyIDentification companyIDentification `xml:"companyIdentification"`
}

// companyIDentification is generated from an XSD element
type companyIDentification struct {
	OtherCompany string `xml:"otherCompany"`
}

// currency is generated from an XSD element
type currency struct {
	FirstCurrencyDetails firstCurrencyDetails `xml:"firstCurrencyDetails"`
}

// firstCurrencyDetails is generated from an XSD element
type firstCurrencyDetails struct {
	CurrencyQualifier string `xml:"currencyQualifier"`
	CurrencyIsoCode   string `xml:"currencyIsoCode"`
}

// penDisInformation is generated from an XSD element
type penDisInformation struct {
	DiscountPenaltyQualifier string                 `xml:"discountPenaltyQualifier"`
	DiscountPenaltyDetails   discountPenaltyDetails `xml:"discountPenaltyDetails"`
}

// discountPenaltyDetails is generated from an XSD element
type discountPenaltyDetails struct {
	Function   string `xml:"function"`
	AmountType string `xml:"amountType"`
	Amount     string `xml:"amount"`
	Rate       string `xml:"rate"`
	Currency   string `xml:"currency"`
}

// monetaryInformation is generated from an XSD element
type monetaryInformation struct {
	MonetaryDetails      monetaryDetails      `xml:"monetaryDetails"`
	OtherMonetaryDetails otherMonetaryDetails `xml:"otherMonetaryDetails"`
}

// monetaryDetails is generated from an XSD element
type monetaryDetails struct {
	TypeQualifier string  `xml:"typeQualifier"`
	Amount        float64 `xml:"amount"`
	Currency      string  `xml:"currency"`
	Location      string  `xml:"location"`
}

// otherMonetaryDetails is generated from an XSD element
type otherMonetaryDetails struct {
	TypeQualifier string  `xml:"typeQualifier"`
	Amount        float64 `xml:"amount"`
	Currency      string  `xml:"currency"`
	Location      string  `xml:"location"`
}

// taxInformation is generated from an XSD element
type taxInformation struct {
	TaxQualifier string  `xml:"taxQualifier"`
	TaxType      taxType `xml:"taxType"`
	TaxNature    string  `xml:"taxNature"`
	TaxData      taxData `xml:"taxData"`
}

// taxType is generated from an XSD element
type taxType struct {
	IsoCountry string `xml:"isoCountry"`
}

// taxData is generated from an XSD element
type taxData struct {
	TaxRate           string `xml:"taxRate"`
	TaxValueQualifier string `xml:"taxValueQualifier"`
}

// dateInformation is generated from an XSD element
type dateInformation struct {
	BusinessSemantic string   `xml:"businessSemantic"`
	DateTime         dateTime `xml:"dateTime"`
}

// dateTime is generated from an XSD element
type dateTime struct {
	Year  string `xml:"year"`
	Month string `xml:"month"`
	Day   string `xml:"day"`
}

// frequentFlyerInformation is generated from an XSD element
type frequentFlyerInformation struct {
	FrequentTravellerDetails frequentTravellerDetails `xml:"frequentTravellerDetails"`
}

// frequentTravellerDetails is generated from an XSD element
type frequentTravellerDetails struct {
	Carrier      string `xml:"carrier"`
	Number       string `xml:"number"`
	TierLevel    string `xml:"tierLevel"`
	PriorityCode string `xml:"priorityCode"`
}

// formOfPaymentInformation is generated from an XSD element
type formOfPaymentInformation struct {
	FormOfPayment      formOfPayment      `xml:"formOfPayment"`
	OtherFormOfPayment otherFormOfPayment `xml:"otherFormOfPayment"`
}

// formOfPayment is generated from an XSD element
type formOfPayment struct {
	Type             string  `xml:"type"`
	Amount           float64 `xml:"amount"`
	CreditCardNumber string  `xml:"creditCardNumber"`
}

// otherFormOfPayment is generated from an XSD element
type otherFormOfPayment struct {
	Type             string  `xml:"type"`
	Amount           float64 `xml:"amount"`
	CreditCardNumber string  `xml:"creditCardNumber"`
}

// locationInformation is generated from an XSD element
type locationInformation struct {
	LocationType          string                `xml:"locationType"`
	FirstLocationDetails  firstLocationDetails  `xml:"firstLocationDetails"`
	SecondLocationDetails secondLocationDetails `xml:"secondLocationDetails"`
}

// firstLocationDetails is generated from an XSD element
type firstLocationDetails struct {
	Code string `xml:"code"`
}

// secondLocationDetails is generated from an XSD element
type secondLocationDetails struct {
	Code string `xml:"code"`
}

// paxSegTstReference is generated from an XSD element
type paxSegTstReference struct {
	ReferenceDetails referenceDetails `xml:"referenceDetails"`
}

// referenceDetails is generated from an XSD element
type referenceDetails struct {
	Type  string `xml:"type"`
	Value string `xml:"value"`
}

// offerReferences is generated from an XSD element
type offerReferences struct {
	OfferIDentifier offerIDentifier `xml:"offerIdentifier"`
}

// offerIDentifier is generated from an XSD element
type offerIDentifier struct {
	Reference            string `xml:"reference"`
	OfferID              string `xml:"offerId"`
	UniqueOfferReference string `xml:"uniqueOfferReference"`
	OfferItemID          string `xml:"offerItemId"`
}

// elementManagementData is generated from an XSD element
type elementManagementData struct {
	Status      int       `xml:"status"`
	Reference   reference `xml:"reference"`
	SegmentName string    `xml:"segmentName"`
	LineNumber  int       `xml:"lineNumber"`
}

// reference is generated from an XSD element
type reference struct {
	Type  string `xml:"type"`
	Value string `xml:"value"`
}
